First update 2022 edition
WISVCH/COD-archive pull request #3
Opened 2022-02-22 15:10 UTC by merelanne

2022-02-22 16:16 UTC, julian9499 requested changes

2022-02-22 16:16 UTC, julian9499 commented on footer.txt
> +document.write('<html><head><title>COD</title><meta name="viewport" content="width=device-width, initial-scale=1"><link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.mi
I would rename footer.txt to footer.js since it is a js file

2022-02-22 16:16 UTC, julian9499 commented on header.txt
> +document.write('<html><head><title>COD</title><meta name="viewport" content="width=device-width, initial-scale=1"><link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.mi
Same here header.js would fit better

2022-02-23 10:33 UTC, MLeBlansch approved these changes

2022-02-24 10:33 UTC, julian9499 approved these changes

2022-02-24 10:33 UTC, merged